// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/layout/header";
import Footer from "./components/layout/Footer";

import "react-toastify/dist/ReactToastify.css";
import { ToastProvider } from "./components/common/ToastProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="antialiased overflow-x-hidden">
        <Header />

        {children}

        <Footer />
        <ToastProvider />
      </body>
    </html>
  );
}
